apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-quotes-db
  labels:
    app: vehicle-quotes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-quotes-db
  template:
    metadata:
      labels:
        app: vehicle-quotes-db
    spec:
      containers:
      - name: vehicle-quotes-db
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: vehicle-quotes-postgres-data-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: vehicle-quotes-postgres-data-storage
        persistentVolumeClaim:
          claimName: vehicle-quotes-postgres-data-persisent-volume-claim
